#!/bin/sh

# Script called by Mender agent to collect device identity data. The script
# needs to be located at
# $(datadir)/mender/identity/mender-device-identity path for the agent to find
# it. The script shall exit with non-0 status on errors. In this case the agent
# will discard any output the script may have produced.
#
# The script shall output identity data in <key>=<value> format, one
# entry per line. Example
#
# $ ./mender-device-identity
# mac=de:ad:ca:fe:00:01
# cpuid=1112233
#
# This script simply prints the "mender_device_identity" U-Boot environment
# variable
#

set -ue

fw_printenv mender_device_identity
